### ISSUE TITLE
cannot deploy memcachedoperator.0.0.1.csv.yaml: operator-lifecycle-manager csv in namespace with no operatorgroups

### ISSUE THREAD

**Issue by hongkailiu** [operator-framework/operator-sdk-samples#57]
```
$ oc get clusterversion 
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.0.0-0.nightly-2019-02-26-104314   True        False         153m    Cluster version is 4.0.0-0.nightly-2019-02-26-104314

$ git clone https://github.com/operator-framework/operator-sdk-samples.git
$ cd operator-sdk-samples/memcached-operator/
$ curl -Lo memcachedoperator.0.0.1.csv.yaml https://raw.githubusercontent.com/operator-framework/getting-started/master/memcachedoperator.0.0.1.csv.yaml
$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml
$ oc get csv 
NAME                       DISPLAY                 VERSION   REPLACES   PHASE
memcachedoperator.v0.0.1   Memcached Application   0.0.1                Failed

$ oc describe csv memcachedoperator.v0.0.1
Name:         memcachedoperator.v0.0.1
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"operators.coreos.com/v1alpha1","kind":"ClusterServiceVersion","metadata":{"annotations":{},"name":"memcachedoperator.v0.0.1...
API Version:  operators.coreos.com/v1alpha1
Kind:         ClusterServiceVersion
Metadata:
  Creation Timestamp:  2019-02-26T15:45:16Z
  Generation:          1
  Resource Version:    126172
  Self Link:           /apis/operators.coreos.com/v1alpha1/namespaces/default/clusterserviceversions/memcachedoperator.v0.0.1
  UID:                 831b93b3-39dd-11e9-8004-028b3db5110a
Spec:
  Customresourcedefinitions:
    Owned:
      Description:   Represents a cluster of Memcached apps
      Display Name:  Memcached App
      Kind:          Memcached
      Name:          memcacheds.cache.example.com
      Resources:
        Kind:     Deployment
        Version:  v1beta2
        Kind:     ReplicaSet
        Version:  v1beta2
        Kind:     Pod
        Version:  v1
      Spec Descriptors:
        Description:   The desired number of member Pods for the deployment.
        Display Name:  Size
        Path:          size
        X - Descriptors:
          urn:alm:descriptor:com.tectonic.ui:podCount
      Status Descriptors:
        Description:   The current status of the application.
        Display Name:  Status
        Path:          phase
        X - Descriptors:
          urn:alm:descriptor:io.kubernetes.phase
        Description:   Explanation for the current status of the application.
        Display Name:  Status Details
        Path:          reason
        X - Descriptors:
          urn:alm:descriptor:io.kubernetes.phase:reason
      Version:   v1alpha1
  Description:   Main enterprise application providing business critical features with high availabilty and no manual intervention.
  Display Name:  Memcached Application
  Install:
    Spec:
      Deployments:
        Name:  memcached-app-operator
        Spec:
          Replicas:  1
          Selector:
            Match Labels:
              App:  memcached-app-operator
          Template:
            Metadata:
              Labels:
                App:  memcached-app-operator
            Spec:
              Containers:
                Command:
                  /usr/local/bin/memcached-operator
                Image:              quay.io/jzelinskie/memcached-operator:v0.0.1
                Image Pull Policy:  Always
                Name:               sao
                Ports:
                  Container Port:                8080
                  Protocol:                      TCP
              Restart Policy:                    Always
              Service Account:                   memcached-operator
              Service Account Name:              memcached-operator
              Termination Grace Period Seconds:  5
      Permissions:
        Rules:
          API Groups:
            *
          Resources:
            *
          Verbs:
            *
        Service Account Name:  memcached-operator
    Strategy:                  deployment
  Keywords:
    memcached
    app
  Labels:
    Alm - Owner - Enterprise - App:  memcached-app-operator
    Alm - Status - Descriptors:      memcached-app-operator.v0.0.1
  Maintainers:
    Email:   corp@example.com
    Name:    Some Corp
  Maturity:  alpha
  Provider:
    Name:   Example
    URL:    www.example.com
  Version:  0.0.1
Status:
  Certs Last Updated:  <nil>
  Certs Rotate At:     <nil>
  Conditions:
    Last Transition Time:  2019-02-26T15:45:16Z
    Last Update Time:      2019-02-26T15:45:16Z
    Message:               csv in namespace with no operatorgroups
    Phase:                 Failed
    Reason:                NoOperatorGroup
  Last Transition Time:    2019-02-26T15:45:16Z
  Last Update Time:        2019-02-26T15:50:28Z
  Message:                 csv in namespace with no operatorgroups
  Phase:                   Failed
  Reason:                  NoOperatorGroup
Events:
  Type     Reason           Age                From                        Message
  ----     ------           ----               ----                        -------
  Warning  NoOperatorGroup  48s (x18 over 6m)  operator-lifecycle-manager  csv in namespace with no operatorgroups


```

Then,

```
$ kubectl get ClusterServiceVersion memcachedoperator.v0.0.1 -o json | jq '.status'
{
  "certsLastUpdated": null,
  "certsRotateAt": null,
  "conditions": [
    {
      "lastTransitionTime": "2019-02-26T15:45:16Z",
      "lastUpdateTime": "2019-02-26T15:45:16Z",
      "message": "csv in namespace with no operatorgroups",
      "phase": "Failed",
      "reason": "NoOperatorGroup"
    }
  ],
  "lastTransitionTime": "2019-02-26T15:45:16Z",
  "lastUpdateTime": "2019-02-26T15:50:28Z",
  "message": "csv in namespace with no operatorgroups",
  "phase": "Failed",
  "reason": "NoOperatorGroup"
}

$ oc project default
$ kubectl create -f deploy/service_account.yaml
serviceaccount/memcached-operator created
$ kubectl create -f deploy/role.yaml
role.rbac.authorization.k8s.io/memcached-operator created
$ kubectl create -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io/memcached-operator created
$ kubectl get ClusterServiceVersion memcachedoperator.v0.0.1 -o json | jq '.status'
{
  "certsLastUpdated": null,
  "certsRotateAt": null,
  "conditions": [
    {
      "lastTransitionTime": "2019-02-26T15:45:16Z",
      "lastUpdateTime": "2019-02-26T15:45:16Z",
      "message": "csv in namespace with no operatorgroups",
      "phase": "Failed",
      "reason": "NoOperatorGroup"
    }
  ],
  "lastTransitionTime": "2019-02-26T15:45:16Z",
  "lastUpdateTime": "2019-02-26T16:00:28Z",
  "message": "csv in namespace with no operatorgroups",
  "phase": "Failed",
  "reason": "NoOperatorGroup"
}

```

**Comment by estroz** [comment]
@hongkailiu unfortunately the `kubectl apply -f csv.yaml` method is outdated, and as far as I know does not work. The https://github.com/operator-framework/getting-started/ guide needs to be updated, if that's what you're following.

The correct way to create a CSV locally is to create a [registry image](https://github.com/estroz/community-operators/blob/scorecard-pr-check/scripts/lib/file#L70) containing your CSV and CRD's, an [`OperatorGroup`](https://github.com/estroz/community-operators/blob/scorecard-pr-check/scripts/lib/file#L50), a [`Subscription`](https://github.com/estroz/community-operators/blob/scorecard-pr-check/scripts/lib/file#L27), and a [`CatalogSource`](https://github.com/estroz/community-operators/blob/scorecard-pr-check/scripts/lib/file#L6); the latter should contain the name of your CSV registry image. You can use the linked functions to do so.

All that being said, I have not tried `kubectl apply -f csv.yaml` after creating an `OperatorGroup`. You can try creating one then applying your CSV. Hope this helps.

**Comment by hongkailiu** [comment]
@estroz thanks. Let me give the new way a shot. At the same time, I am trying the community way as well.

**Comment by hongkailiu** [comment]
@estroz Probably this is not relevant to the original issue. Let me know if I need to create another one.

```
https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md

$ ll $BUNDLE_DIR
total 24
-rw-rw-r--. 1 hongkliu hongkliu   629 Feb 25 14:35 svt-app-operator.crd.yaml
-rw-rw-r--. 1 hongkliu hongkliu    95 Feb 26 01:17 svt-app-operator.package.yaml
-rw-rw-r--. 1 hongkliu hongkliu 15669 Feb 26 15:20 svt-app-operator.v0.0.2.clusterserviceversion.yaml

$ operator-courier verify $BUNDLE_DIR

$ AUTH_TOKEN=$(curl -sH "Content-Type: application/json" -XPOST https://quay.io/cnr/api/v1/users/login -d '
> {
>     "user": {
>         "username": "'"${QUAY_USERNAME}"'",
>         "password": "'"${QUAY_PASSWORD}"'"
>     }
> }' | jq -r '.token')


$ echo $AUTH_TOKEN
basic ***==

$ EXAMPLE_NAMESPACE=hongkailiu
$ EXAMPLE_REPOSITORY=svt-app-operator
$ EXAMPLE_RELEASE=0.0.2
$ operator-courier push $BUNDLE_DIR $EXAMPLE_NAMESPACE $EXAMPLE_REPOSITORY $EXAMPLE_RELEASE $AUTH_TOKEN
ERROR:operatorcourier.push:{"error":{"code":"forbidden","details":{"package":"hongkailiu/svt-app-operator","scopes":["push"]},"message":"Unauthorized access for: hongkailiu/svt-app-operator"}}

Traceback (most recent call last):
  File "/home/hongkliu/p3env/bin/operator-courier", line 10, in <module>
    sys.exit(main())
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 9, in main
    parser.parse()
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 36, in parse
    getattr(self, args.command)()
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/cli.py", line 56, in push
    api.build_verify_and_push(args.namespace, args.repository, args.release, args.token, source_dir=args.source_dir)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/api.py", line 73, in build_verify_and_push
    PushCmd().push(temp_dir, namespace, repository, revision, token)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/push.py", line 27, in push
    self._push_to_registry(namespace, repository, release, base64_bundle, auth_token)
  File "/home/hongkliu/p3env/lib/python3.7/site-packages/operatorcourier/push.py", line 56, in _push_to_registry
    raise ValueError("Failed to push to app registry: {}".format(msg))
ValueError: Failed to push to app registry: Quay.io answered: 'forbidden' (Unauthorized access for: hongkailiu/svt-app-operator)

```

**Comment by hongkailiu** [comment]
```
$ echo $BUNDLE_DIR
/home/hongkliu/go/src/github.com/hongkailiu/operators/svt-app-operator/deploy/BUNDLE_DIR
```

**Comment by hongkailiu** [comment]
Totally working. Thanks @estroz 

```
# oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.0.0-0.nightly-2019-02-27-213933   True        False         3h4m    Cluster version is 4.0.0-0.nightly-2019-02-27-213933

# oc new-project ccc
# cat ~/operatorGroup.yaml 
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: SVT.v1alpha1.app.test.com
  generation: 2
  name: myog
spec:
  selector: {}
  targetNamespaces:
  - ccc

# oc create -f ~/operatorGroup.yaml

# cat ~/catalogSource.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    csc-owner-name: installed-custom-ccc
    csc-owner-namespace: openshift-marketplace
  name: installed-custom-ccc
spec:
  address: 172.30.195.68:50051
  displayName: Custom Operators
  icon:
    base64data: ""
    mediatype: ""
  publisher: Custom
  sourceType: grpc

# oc create -f ~/catalogSource.yaml

# cat ~/subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: svt-app-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: svt-app-operator
  source: installed-custom-ccc
  sourceNamespace: ccc
  startingCSV: svt-app-operator.v0.0.8

# oc create -f ~/subscription.yaml

### csv got created automatically
# oc get csv
NAME                      DISPLAY           VERSION   REPLACES   PHASE
svt-app-operator.v0.0.8   SVT Application   0.0.8                Succeeded
# oc get pod
NAME                                READY   STATUS    RESTARTS   AGE
svt-app-operator-56c5b995c8-fvcsh   1/1     Running   0          63s

### We can start to delpy our crd and check as before
# oc create -f deploy/crds/app_v1alpha1_svt_cr.yaml 
```
