### ISSUE TITLE
Go Memcached CSV improvements (discussions)

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk-samples#89]
This task is for we track the current discussion over how should we dealing with. 
This thread started at: https://github.com/operator-framework/operator-sdk-samples/pull/82/files#r341319166

- Should we version all CSV files according to the Memcached released?
- Should we change the name of the channels?

**Comment by camilamacedo86** [comment]
From @joelanford:

> To be totally honest, I think it's a little weird to have CSVs per SDK version since that isn't how a "real" operator would do things. +1 @camilamacedo86 

Regards the CSV the suggestion shows be changed the name for the spec.version  in the CSV and does as follows. 

```yaml
channels:
- currentCSV: memcached-operator.v0.11.0
  name: v0.11.x
- currentCSV: memcached-operator.v0.10.0
  name: v0.10.x
defaultChannel: v0.11.x
```

**Comment by camilamacedo86** [comment]
From @estroz (last questions so far)

> @joelanford what you're implying is that we should update the alpha channel with the new CSV version on each release?
> 
> An issue crops up here with the CSV's spec.replaces. If OLM can't resolve a CSV specified in spec.replaces, then installation will fail. So each spec.replaces must reference a CSV name contained in the package manifest's channels. That is why I suggested we use versioned channel names. We may have to remove spec.replaces from all CSV versions if we do not want to also expand the number of channels.

**Comment by estroz** [comment]
In reference to ^: I recently found out about `spec.skips` and `metadata.annotations["olm.skipRange"]`, both allowing a CSV to specify CSV versions to skip. I recommend using the latter so we can say "ignore CSV's below v0.11.0" with:

```yaml
metadata:
    annotations:
        olm.skipRange: '<0.11.0'
```

We can still remove `spec.replaces` so we can always have one `alpha` channel for the current CSV in the package manifest. Just figured I'd point out this useful feature.
